#!/usr/bin/python3
#SPDX-FileCopyrightText: 2024 Yukimi Miyahara
# SPDX-License-Identifier: BSD-3-Clause

import sys

MONTH = {"1" : "January", "2" : "February", "3" : "March", "4" : "April", "5" : "May", "6" : "June", "7" : "July", "8" : "August", "9" : "September", "10" : "October", "11" : "November", "12" : "December"}

for date in sys.stdin:
    date = date.rstrip()
    print(MONTH[date])
    



